spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rCaFjnHqeYrDGDjxDxiiLrwbkDQONumF
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=ShopKartSecretKeyForJWTSigningMustBe256BitsOrMoreForHS256Algorithm2024!
app.jwt.expiration=86400000
app.upload.dir=src/main/resources/static/uploads
app.cors.allowed-origins=app.cors.allowed-origins=http://localhost:3000,https://shop-cart-e-commerce-platform.vercel.app,https://shop-ix.vercel.app
app.telegram.bot-token=8731924093:AAGbGVXTt0nWsr14MeLep3viac8tbGY0enY
app.telegram.chat-id=1831365798
