spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:PORT/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=pjHFjBkpAcuNtkqdJWzuddNgqODnZriv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
